FROM bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8

ENV CLUSTER_NAME=mlops-cluster
ENV CORE_CONF_fs_defaultFS=hdfs://namenode:9000
ENV HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
ENV HDFS_CONF_dfs_replication=1

EXPOSE 9864 9866

CMD ["/entrypoint.sh"]
