FROM bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8

ENV CLUSTER_NAME=mlops-cluster
ENV CORE_CONF_fs_defaultFS=hdfs://namenode:9000
ENV HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
ENV HDFS_CONF_dfs_replication=1

EXPOSE 9870 9000

CMD ["/entrypoint.sh"]
